name = "redirect"
main = "src/index.js"
compatibility_date = "2022-12-03"
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]

# The necessary secrets are:
# SUPABASE_ENDPOINT
# SUPABASE_PUBLIC_ANON_KEY